#Requires AutoHotkey v2.0

Class ObjectItem {
    name := ""
    type := ""
    pointX := 0
    pointY := 0
    pointXOffsetFromMatch := 0
    pointYOffsetFromMatch := 0
    rangeX1 := 0
    rangeY1 := 0
    rangeX2 := 0
    rangeY2 := 0
    matchImage := VarRef
    matchTolerance := 5
}

FriendRequestListCard := ObjectItem()
FriendRequestListClearButton := ObjectItem()
UserDetailEmblem := ObjectItem()
UserDetailMybest1 := ObjectItem()
UserDetailMybest2 := ObjectItem()
UserDetailMybestButton1 := ObjectItem()
UserDetailMybestButton2 := ObjectItem()
PassportPikachu := ObjectItem()
UserDetailAccept := ObjectItem()
UserDetailDecline := ObjectItem()
UserDetailRequestFriend := ObjectItem()
UserDetailFriendNow := ObjectItem()
UserDetailEmpty1 := ObjectItem()
UserDetailEmpty2 := ObjectItem()
UserDetailRequestNotFound := ObjectItem()
FriendsMenuButton := ObjectItem()
FriendListCard := ObjectItem()
RemoveFriendConfirm := ObjectItem()
FriendRequestListEmpty := ObjectItem()
FriendListEmpty := ObjectItem()
FriendRequestMenuButton := ObjectItem()
DialogConfirmButton := ObjectItem()
FriendRequestListActive := ObjectItem()
FriendListActive := ObjectItem()

ObjectLibrary := {}
ObjectLibrary.FriendRequestListCard := FriendRequestListCard
ObjectLibrary.FriendRequestListClearButton := FriendRequestListClearButton
ObjectLibrary.UserDetailEmblem := UserDetailEmblem
ObjectLibrary.UserDetailMybest1 := UserDetailMybest1
ObjectLibrary.UserDetailMybest2 := UserDetailMybest2
ObjectLibrary.UserDetailMybestButton1 := UserDetailMybestButton1
ObjectLibrary.UserDetailMybestButton2 := UserDetailMybestButton2
ObjectLibrary.PassportPikachu := PassportPikachu
ObjectLibrary.UserDetailAccept := UserDetailAccept
ObjectLibrary.UserDetailDecline := UserDetailDecline
ObjectLibrary.UserDetailRequestFriend := UserDetailRequestFriend
ObjectLibrary.UserDetailFriendNow := UserDetailFriendNow
ObjectLibrary.UserDetailEmpty1 := UserDetailEmpty1
ObjectLibrary.UserDetailEmpty2 := UserDetailEmpty2
ObjectLibrary.FriendsMenuButton := FriendsMenuButton
ObjectLibrary.FriendListCard := FriendListCard
ObjectLibrary.RemoveFriendConfirm := RemoveFriendConfirm
ObjectLibrary.FriendRequestListEmpty := FriendRequestListEmpty
ObjectLibrary.FriendListEmpty := FriendListEmpty
ObjectLibrary.FriendRequestMenuButton := FriendRequestMenuButton
ObjectLibrary.DialogConfirmButton := DialogConfirmButton
ObjectLibrary.FriendRequestListActive := FriendRequestListActive
ObjectLibrary.UserDetailRequestNotFound := UserDetailRequestNotFound
ObjectLibrary.FriendListActive := FriendListActive

ImageSet_FriendRequestListCard := Map('4K', A_ScriptDir "\asset\match\4k\FriendRequestListCard.png", 'QHD', A_ScriptDir "\asset\match\qhd\FriendRequestListCard.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\FriendRequestListCard.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\FriendRequestListCard.png")
ImageFile_FriendRequestListClearButton := Map('4K', A_ScriptDir "\asset\match\4k\FriendRequestListClearButton.png", 'QHD', A_ScriptDir "\asset\match\qhd\FriendRequestListClearButton.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\FriendRequestListClearButton.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\FriendRequestListClearButton.png")
ImageFile_UserDetailEmblem := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailEmblem.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailEmblem.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailEmblem.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailEmblem.png")
ImageFile_UserDetailMybest1 := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailMybest1.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailMybest1.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailMybest1.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailMybest1.png")
ImageFile_UserDetailMybest2 := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailMybest2.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailMybest2.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailMybest2.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailMybest2.png")
ImageFile_UserDetailMybestButton1 := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailMybestButton1.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailMybestButton1.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailMybestButton1.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailMybestButton1.png")
ImageFile_UserDetailMybestButton2 := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailMybestButton2.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailMybestButton2.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailMybestButton2.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailMybestButton2.png")
ImageFile_PassportPikachu := Map('4K', A_ScriptDir "\asset\match\4k\PassportPikachu.png", 'QHD', A_ScriptDir "\asset\match\qhd\PassportPikachu.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\PassportPikachu.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\PassportPikachu.png")
ImageFile_UserDetailAccept := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailAccept.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailAccept.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailAccept.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailAccept.png")
ImageFile_UserDetailDecline := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailDecline.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailDecline.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailDecline.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailDecline.png")
ImageFile_UserDetailRequestFriend := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailRequestFriend.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailRequestFriend.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailRequestFriend.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailRequestFriend.png")
ImageFile_UserDetailFriendNow := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailFriendNow.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailFriendNow.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailFriendNow.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailFriendNow.png")
ImageFile_UserDetailEmpty1 := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailEmpty1.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailEmpty1.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailEmpty1.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailEmpty1.png")
ImageFile_UserDetailEmpty2 := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailEmpty2.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailEmpty2.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailEmpty2.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailEmpty2.png")
ImageFile_FriendsMenuButton := Map('4K', A_ScriptDir "\asset\match\4k\FriendsMenuButton.png", 'QHD', A_ScriptDir "\asset\match\qhd\FriendsMenuButton.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\FriendsMenuButton.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\FriendsMenuButton.png")
ImageFile_FriendListCard := Map('4K', A_ScriptDir "\asset\match\4k\FriendListCard.png", 'QHD', A_ScriptDir "\asset\match\qhd\FriendListCard.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\FriendListCard.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\FriendListCard.png")
ImageFile_RemoveFriendConfirm := Map('4K', A_ScriptDir "\asset\match\4k\RemoveFriendConfirm.png", 'QHD', A_ScriptDir "\asset\match\qhd\RemoveFriendConfirm.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\RemoveFriendConfirm.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\RemoveFriendConfirm.png")
ImageFile_FriendRequestListEmpty := Map('4K', A_ScriptDir "\asset\match\4k\FriendRequestListEmpty.png", 'QHD', A_ScriptDir "\asset\match\qhd\FriendRequestListEmpty.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\FriendRequestListEmpty.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\FriendRequestListEmpty.png")
ImageFile_FriendListEmpty := Map('4K', A_ScriptDir "\asset\match\4k\FriendListEmpty.png", 'QHD', A_ScriptDir "\asset\match\qhd\FriendListEmpty.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\FriendListEmpty.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\FriendListEmpty.png")
ImageFile_FriendRequestListActive := Map('4K', A_ScriptDir "\asset\match\4k\FriendRequestListActive.png", 'QHD', A_ScriptDir "\asset\match\qhd\FriendRequestListActive.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\FriendRequestListActive.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\FriendRequestListActive.png")
ImageFile_UserDetailRequestNotFound := Map('4K', A_ScriptDir "\asset\match\4k\UserDetailRequestNotFound.png", 'QHD', A_ScriptDir "\asset\match\qhd\UserDetailRequestNotFound.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\UserDetailRequestNotFound.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\UserDetailRequestNotFound.png")
ImageFile_FriendListActive := Map('4K', A_ScriptDir "\asset\match\4k\FriendListActive.png", 'QHD', A_ScriptDir "\asset\match\qhd\FriendListActive.png",'FHD-100', A_ScriptDir "\asset\match\fhd-100\FriendListActive.png",'FHD-125', A_ScriptDir "\asset\match\fhd-125\FriendListActive.png")


; // 템플릿
; ItemNameHere.name := "ItemNameHere"
; ItemNameHere.type := "Anchor" / "Button"
; ItemNameHere.pointX := 
; ItemNameHere.pointY := 
; ItemNameHere.pointXOffsetFromMatch := 
; ItemNameHere.pointYOffsetFromMatch := 
; ItemNameHere.rangeX1 := 
; ItemNameHere.rangeY1 := 
; ItemNameHere.rangeX2 := 
; ItemNameHere.rangeY2 := 
; ItemNameHere.matchImage := 
; ItemNameHere.matchTolerance := 


FriendRequestListCard.name := "FriendRequestListCard"
FriendRequestListCard.type := "Button"
FriendRequestListCard.pointX := .63
FriendRequestListCard.pointY := .21
FriendRequestListCard.pointXOffsetFromMatch := -.03
FriendRequestListCard.pointYOffsetFromMatch := -.03
FriendRequestListCard.rangeX1 := .60
FriendRequestListCard.rangeY1 := .20
FriendRequestListCard.rangeX2 := .99
FriendRequestListCard.rangeY2 := .35
FriendRequestListCard.matchImage := ImageSet_FriendRequestListCard
FriendRequestListCard.matchTolerance := 10

FriendRequestListClearButton.name := "FriendRequestListClearButton"
FriendRequestListClearButton.type := "Button"
; FriendRequestListClearButton.pointX := 
; FriendRequestListClearButton.pointY := 
; FriendRequestListClearButton.pointXOffsetFromMatch := .01
; FriendRequestListClearButton.pointYOffsetFromMatch := .01
FriendRequestListClearButton.rangeX1 := .60
FriendRequestListClearButton.rangeY1 := .85
FriendRequestListClearButton.rangeX2 := .99
FriendRequestListClearButton.rangeY2 := .99
FriendRequestListClearButton.matchImage := ImageFile_FriendRequestListClearButton
FriendRequestListClearButton.matchTolerance := 10

; userDetailEmblem.name := "userDetailEmblem"
; userDetailEmblem.type := "Anchor"
; ; userDetailEmblem.pointX := 
; ; userDetailEmblem.pointY := 
; ; userDetailEmblem.pointXOffsetFromMatch := 
; ; userDetailEmblem.pointYOffsetFromMatch := 
; userDetailEmblem.rangeX1 := 
; userDetailEmblem.rangeY1 := 
; userDetailEmblem.rangeX2 := 
; userDetailEmblem.rangeY2 := 
; userDetailEmblem.matchImage := ImageFile_userDetailEmblem
UserDetailEmblem.matchTolerance := 10

PassportPikachu.name := "PassportPikachu"
PassportPikachu.type := "Anchor"
; PassportPikachu.pointX := 
; PassportPikachu.pointY := 
; PassportPikachu.pointXOffsetFromMatch := 
; PassportPikachu.pointYOffsetFromMatch := 
PassportPikachu.rangeX1 := .04
PassportPikachu.rangeY1 := .62
PassportPikachu.rangeX2 := .25
PassportPikachu.rangeY2 := .66
PassportPikachu.matchImage := ImageFile_PassportPikachu
PassportPikachu.matchTolerance := 20

UserDetailAccept.name := "UserDetailAccept"
UserDetailAccept.type := "Button"
UserDetailAccept.pointX := .70
UserDetailAccept.pointY := .57
UserDetailAccept.pointXOffsetFromMatch := .05
UserDetailAccept.pointYOffsetFromMatch := .01
UserDetailAccept.rangeX1 := .05
UserDetailAccept.rangeY1 := .50
UserDetailAccept.rangeX2 := .95
UserDetailAccept.rangeY2 := .65
UserDetailAccept.matchImage := ImageFile_UserDetailAccept
UserDetailAccept.matchTolerance := 10

UserDetailDecline.name := "UserDetailDecline"
UserDetailDecline.type := "Button"
UserDetailDecline.pointX := .30
UserDetailDecline.pointY := .57
UserDetailDecline.pointXOffsetFromMatch := .01
UserDetailDecline.pointYOffsetFromMatch := .01
UserDetailDecline.rangeX1 := .05
UserDetailDecline.rangeY1 := .50
UserDetailDecline.rangeX2 := .95
UserDetailDecline.rangeY2 := .65
UserDetailDecline.matchImage := ImageFile_UserDetailDecline
UserDetailDecline.matchTolerance := 10

UserDetailRequestFriend.name := "UserDetailRequestFriend"
UserDetailRequestFriend.type := "Button"
UserDetailRequestFriend.pointX := .50
UserDetailRequestFriend.pointY := .57
UserDetailRequestFriend.pointXOffsetFromMatch := .01
UserDetailRequestFriend.pointYOffsetFromMatch := .01
UserDetailRequestFriend.rangeX1 := .05
UserDetailRequestFriend.rangeY1 := .50
UserDetailRequestFriend.rangeX2 := .95
UserDetailRequestFriend.rangeY2 := .65
UserDetailRequestFriend.matchImage := ImageFile_UserDetailRequestFriend
UserDetailRequestFriend.matchTolerance := 10

UserDetailFriendNow.name := "UserDetailFriendNow"
UserDetailFriendNow.type := "Button"
UserDetailFriendNow.pointX := .50
UserDetailFriendNow.pointY := .57
UserDetailFriendNow.pointXOffsetFromMatch := .01
UserDetailFriendNow.pointYOffsetFromMatch := .01
UserDetailFriendNow.rangeX1 := .20
UserDetailFriendNow.rangeY1 := .50
UserDetailFriendNow.rangeX2 := .80
UserDetailFriendNow.rangeY2 := .65
UserDetailFriendNow.matchImage := ImageFile_UserDetailFriendNow
UserDetailFriendNow.matchTolerance := 10

UserDetailMybest1.name := "UserDetailMybest1"
UserDetailMybest1.type := "Anchor"
; UserDetailMybest1.pointX := 
; UserDetailMybest1.pointY := 
; UserDetailMybest1.pointXOffsetFromMatch := 
; UserDetailMybest1.pointYOffsetFromMatch := 
UserDetailMybest1.rangeX1 := .15
UserDetailMybest1.rangeY1 := .60
UserDetailMybest1.rangeX2 := .85
UserDetailMybest1.rangeY2 := .90
UserDetailMybest1.matchImage := ImageFile_UserDetailMybest2
UserDetailMybest1.matchTolerance := 20

UserDetailMybest2.name := "UserDetailMybest2"
UserDetailMybest2.type := "Anchor"
; UserDetailMybest2.pointX := 
; UserDetailMybest2.pointY := 
; UserDetailMybest2.pointXOffsetFromMatch := 
; UserDetailMybest2.pointYOffsetFromMatch := 
UserDetailMybest2.rangeX1 := .25
UserDetailMybest2.rangeY1 := .60
UserDetailMybest2.rangeX2 := .85
UserDetailMybest2.rangeY2 := .90
UserDetailMybest2.matchImage := ImageFile_UserDetailMybest2
UserDetailMybest2.matchTolerance := 20

UserDetailMybestButton1.name := "UserDetailMybestButton1"
UserDetailMybestButton1.type := "Button"
UserDetailMybestButton1.pointX := .70
UserDetailMybestButton1.pointY := .96
UserDetailMybestButton1.pointXOffsetFromMatch := .0
UserDetailMybestButton1.pointYOffsetFromMatch := .05
UserDetailMybestButton1.rangeX1 := .64
UserDetailMybestButton1.rangeY1 := .85
UserDetailMybestButton1.rangeX2 := .78
UserDetailMybestButton1.rangeY2 := .95
UserDetailMybestButton1.matchImage := ImageFile_UserDetailMybestButton1
UserDetailMybestButton1.matchTolerance := 10

UserDetailMybestButton2.name := "UserDetailMybestButton2"
UserDetailMybestButton2.type := "Button"
UserDetailMybestButton2.pointX := .50
UserDetailMybestButton2.pointY := .85
UserDetailMybestButton2.pointXOffsetFromMatch := -.1
UserDetailMybestButton2.pointYOffsetFromMatch := -.05
UserDetailMybestButton2.rangeX1 := .64
UserDetailMybestButton2.rangeY1 := .75
UserDetailMybestButton2.rangeX2 := .78
UserDetailMybestButton2.rangeY2 := .85
UserDetailMybestButton2.matchImage := ImageFile_UserDetailMybestButton2
UserDetailMybestButton2.matchTolerance := 10

UserDetailEmpty1.name := "UserDetailEmpty1"
UserDetailEmpty1.type := "Anchor"
; UserDetailEmpty1.pointX := 
; UserDetailEmpty1.pointY := 
; UserDetailEmpty1.pointXOffsetFromMatch := 
; UserDetailEmpty1.pointYOffsetFromMatch := 
UserDetailEmpty1.rangeX1 := .25
UserDetailEmpty1.rangeY1 := .60
UserDetailEmpty1.rangeX2 := .85
UserDetailEmpty1.rangeY2 := .90
UserDetailEmpty1.matchImage := ImageFile_UserDetailEmpty1
UserDetailEmpty1.matchTolerance := 20

UserDetailEmpty2.name := "UserDetailEmpty2"
UserDetailEmpty2.type := "Anchor"
; UserDetailEmpty2.pointX := 
; UserDetailEmpty2.pointY := 
; UserDetailEmpty2.pointXOffsetFromMatch := 
; UserDetailEmpty2.pointYOffsetFromMatch := 
UserDetailEmpty2.rangeX1 := .25
UserDetailEmpty2.rangeY1 := .60
UserDetailEmpty2.rangeX2 := .85
UserDetailEmpty2.rangeY2 := .90
UserDetailEmpty2.matchImage := ImageFile_UserDetailEmpty2
UserDetailEmpty2.matchTolerance := 20

FriendsMenuButton.name := "FriendsMenuButton"
FriendsMenuButton.type := "Button"
FriendsMenuButton.pointX := .13
FriendsMenuButton.pointY := .90
FriendsMenuButton.pointXOffsetFromMatch := .01
FriendsMenuButton.pointYOffsetFromMatch := .01
FriendsMenuButton.rangeX1 := .01
FriendsMenuButton.rangeY1 := .80
FriendsMenuButton.rangeX2 := .30
FriendsMenuButton.rangeY2 := .95
FriendsMenuButton.matchImage := ImageFile_FriendsMenuButton
FriendsMenuButton.matchTolerance := 10

FriendListCard.name := "FriendListCard"
FriendListCard.type := "Button"
FriendListCard.pointX := .63
FriendListCard.pointY := .21
FriendListCard.pointXOffsetFromMatch := -.01
FriendListCard.pointYOffsetFromMatch := -.02
FriendListCard.rangeX1 := .55
FriendListCard.rangeY1 := .25
FriendListCard.rangeX2 := .99
FriendListCard.rangeY2 := .35
FriendListCard.matchImage := ImageFile_FriendListCard
FriendListCard.matchTolerance := 10

RemoveFriendConfirm.name := "RemoveFriendConfirm"
RemoveFriendConfirm.type := "Button"
RemoveFriendConfirm.pointX := .72
RemoveFriendConfirm.pointY := .63
RemoveFriendConfirm.pointXOffsetFromMatch := .01
RemoveFriendConfirm.pointYOffsetFromMatch := .01
RemoveFriendConfirm.rangeX1 := .45
RemoveFriendConfirm.rangeY1 := .55
RemoveFriendConfirm.rangeX2 := .100
RemoveFriendConfirm.rangeY2 := .70
RemoveFriendConfirm.matchImage := ImageFile_RemoveFriendConfirm
RemoveFriendConfirm.matchTolerance := 10

FriendRequestListEmpty.name := "FriendRequestListEmpty"
FriendRequestListEmpty.type := "Anchor"
; FriendRequestListEmpty.pointX := 
; FriendRequestListEmpty.pointY := 
FriendRequestListEmpty.pointXOffsetFromMatch := .01
FriendRequestListEmpty.pointYOffsetFromMatch := .01
FriendRequestListEmpty.rangeX1 := .15
FriendRequestListEmpty.rangeY1 := .45
FriendRequestListEmpty.rangeX2 := .80
FriendRequestListEmpty.rangeY2 := .60
FriendRequestListEmpty.matchImage := ImageFile_FriendRequestListEmpty
FriendRequestListEmpty.matchTolerance := 10

FriendListEmpty.name := "FriendListEmpty"
FriendListEmpty.type := "Anchor"
; FriendListEmpty.pointX := 
; FriendListEmpty.pointY := 
FriendListEmpty.pointXOffsetFromMatch := .01
FriendListEmpty.pointYOffsetFromMatch := .01
FriendListEmpty.rangeX1 := .15
FriendListEmpty.rangeY1 := .45
FriendListEmpty.rangeX2 := .80
FriendListEmpty.rangeY2 := .60
FriendListEmpty.matchImage := ImageFile_FriendListEmpty
FriendListEmpty.matchTolerance := 10

FriendRequestMenuButton.name := "FriendRequestMenuButton"
FriendRequestMenuButton.type := "Button"
FriendRequestMenuButton.pointX := .82
FriendRequestMenuButton.pointY := .90
; FriendRequestMenuButton.pointXOffsetFromMatch := 
; FriendRequestMenuButton.pointYOffsetFromMatch := 
; FriendRequestMenuButton.rangeX1 := 
; FriendRequestMenuButton.rangeY1 := 
; FriendRequestMenuButton.rangeX2 := 
; FriendRequestMenuButton.rangeY2 := 
; FriendRequestMenuButton.matchImage := 
; FriendRequestMenuButton.matchTolerance := 

DialogConfirmButton.name := "DialogConfirmButton"
DialogConfirmButton.type := "Button"
DialogConfirmButton.pointX := .50
DialogConfirmButton.pointY := .63
; DialogConfirmButton.pointXOffsetFromMatch := 
; DialogConfirmButton.pointYOffsetFromMatch := 
; DialogConfirmButton.rangeX1 := 
; DialogConfirmButton.rangeY1 := 
; DialogConfirmButton.rangeX2 := 
; DialogConfirmButton.rangeY2 := 
; DialogConfirmButton.matchImage := 
; DialogConfirmButton.matchTolerance := 

FriendRequestListActive.name := "FriendRequestListActive"
FriendRequestListActive.type := "Anchor"
; FriendRequestListActive.pointX := 
; FriendRequestListActive.pointY := 
; FriendRequestListActive.pointXOffsetFromMatch := 
; FriendRequestListActive.pointYOffsetFromMatch := 
FriendRequestListActive.rangeX1 := .73
FriendRequestListActive.rangeY1 := .87
FriendRequestListActive.rangeX2 := .88
FriendRequestListActive.rangeY2 := .91
FriendRequestListActive.matchImage := ImageFile_FriendRequestListActive
; FriendRequestListActive.matchTolerance := 

UserDetailRequestNotFound.name := "UserDetailRequestNotFound"
UserDetailRequestNotFound.type := "Button"
UserDetailRequestNotFound.pointX := .50
UserDetailRequestNotFound.pointY := .63
; UserDetailRequestNotFound.pointXOffsetFromMatch := 
; UserDetailRequestNotFound.pointYOffsetFromMatch := 
UserDetailRequestNotFound.rangeX1 := .25
UserDetailRequestNotFound.rangeY1 := .44
UserDetailRequestNotFound.rangeX2 := .75
UserDetailRequestNotFound.rangeY2 := .48
UserDetailRequestNotFound.matchImage := ImageFile_UserDetailRequestNotFound
; UserDetailRequestNotFound.matchTolerance := 

FriendListActive.name := "FriendListActive"
FriendListActive.type := "Anchor"
; FriendListActive.pointX := 
; FriendListActive.pointY := 
; FriendListActive.pointXOffsetFromMatch := 
; FriendListActive.pointYOffsetFromMatch := 
FriendListActive.rangeX1 := .14
FriendListActive.rangeY1 := .87
FriendListActive.rangeX2 := .26
FriendListActive.rangeY2 := .91
FriendListActive.matchImage := ImageFile_FriendListActive
; FriendListActive.matchTolerance := 